kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-mongodb-operator
subjects:
- kind: ServiceAccount
  name: ibm-mongodb-operator
  namespace: ibm-mongodb-operator
roleRef:
  kind: ClusterRole
  name: ibm-mongodb-operator
  apiGroup: rbac.authorization.k8s.io